services:
    emailengine:
        restart: always
        image: postalsys/emailengine:latest
        ports:
            # API and web interface
            # outward/inward ports
            - '4000:3000'
            # SMTP for message submission
            - '2525:2525'
        depends_on:
            - redis
            - elasticsearch
            # - kibana
        # For local development,
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            # Configuration to EmailEngine can be passed via environment variables
            # For full list see https://github.com/postalsys/emailengine#config-mapping
            # Settings to write to v1/settings on startup (https://api.emailengine.app/#operation/postV1Settings)
            # The following value is a YAML block scalar string, so make it sure it is properly indented
            EENGINE_SETTINGS: >
                {
                    "smtpServerEnabled": true,
                    "smtpServerPort": 2525,
                    "smtpServerHost": "0.0.0.0",
                    "smtpServerAuthEnabled": true,
                    "smtpServerPassword": "${SMTP_SERVER_PASSWORD}",
                    "serviceUrl": "${SERVICE_URL}",
                    "webhooksEnabled": true,
                    "webhooks": "${WEBHOOK_URL}",
                    "documentStoreEnabled": true,
                    "documentStoreUrl": "${DOCUMENT_STORE_URL}",
                    "documentStoreAuthEnabled": true,
                    "documentStoreUsername": "${DOCUMENT_STORE_USERNAME}",
                    "documentStorePassword": "${ELASTIC_PASSWORD}"
                }

            # Encryption secret
            EENGINE_SECRET: '${EENGINE_SECRET}'
            # Database connection URL
            EENGINE_REDIS: 'redis://redis:6379/2'

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - /data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
        container_name: elasticsearch
        environment:
            - 'discovery.type=single-node'
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}'
            - 'xpack.security.enabled=${XPACK_SECURITY_ENABLED}'
        ports:
            - ${ES_PORT}:${ES_PORT}
        volumes:
            - esdata:/usr/share/elasticsearch/data

    # Kibana now requires a service key which is a pain to get from elastic search, so let's not activate yet.
    # Error: value of "elastic" is forbidden. This is a superuser account that cannot write to system indices that Kibana needs to function. Use a service account token instead. Learn more: https://www.elastic.co/guide/en/elasticsearch/reference/8.0/service-accounts.html
    # kibana:
    #     env_file:
    #         - ../.env.local

    #     image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    #     container_name: kibana
    #     environment:
    #         - 'ELASTICSEARCH_HOSTS=http://elasticsearch:${ES_PORT}'
    #         - 'ELASTICSEARCH_USERNAME=elastic'
    #         - 'ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}'
    #     ports:
    #         - ${KIBANA_PORT}:${KIBANA_PORT}
    #     networks:
    #         - elastic

volumes:
    esdata:
