// Generated by https://quicktype.io
export type InstagramPostScrape = InstagramPostScrapeData[];
export interface InstagramPostScrapeData {
    id: string;
    type: string;
    shortCode: string;
    caption: string;
    hashtags: string[];
    mentions: string[];
    url: string;
    commentsCount: number;
    firstComment: string;
    latestComments: LatestComment[];
    dimensionsHeight: number;
    dimensionsWidth: number;
    displayUrl: string;
    images: any[];
    videoUrl: string;
    alt: null;
    likesCount: number;
    videoViewCount: number;
    videoPlayCount: number;
    timestamp: string;
    childPosts: any[];
    locationName: string;
    locationId: string;
    ownerFullName: string;
    ownerUsername: string;
    ownerId: string;
    productType: string;
    videoDuration: number;
    isSponsored: boolean;
    taggedUsers: TaggedUser[];
}

export interface LatestComment {
    id: string;
    text: string;
    ownerUsername: string;
    timestamp: string;
    likesCount: number;
    repliesCount?: number;
    replies?: Reply[];
}

export interface Reply {
    id: string;
    text: string;
    ownerUsername: string;
    timestamp: string;
    likesCount: number;
}

export interface TaggedUser {
    full_name: string;
    id: string;
    is_verified: boolean;
    profile_pic_url: string;
    username: string;
}
