// Generated by https://quicktype.io
export type YoutubeVideoScrapeRaw = outubeVideoScrapeStats[];
export interface outubeVideoScrapeStats {
    title: string;
    id: string;
    url: string;
    thumbnailUrl: string;
    viewCount: number;
    date: string;
    likes: number;
    dislikes: null | number;
    location: null;
    channelName: string;
    channelUrl: string;
    numberOfSubscribers: number;
    duration: string;
    commentsCount: number;
    details: string;
    text: string;
    subtitles: null;
    comments: null;
    commentsTurnedOff: boolean;
}
