version: '3.7'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
        environment:
            - 'ES_JAVA_OPTS=-Xms2g -Xmx4g'
            - discovery.type=single-node
            - xpack.security.http.ssl.enabled=false
            - xpack.security.enabled=true
            - ELASTIC_PASSWORD=${ELASTIC_SUPERADMIN_PASSWORD}
        volumes:
            - ./volumes/elasticsearch_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            default:

    kibana:
        image: docker.elastic.co/kibana/kibana:8.12.2
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=${ELASTIC_KIBANA_PASSWORD}
            - server.publicBaseUrl=https://kibana.analytics.productzillaacademy.com
            - SERVER_NAME=kibana.analytics.productzillaacademy.com
            - SERVER_PUBLICBASEURL=https://kibana.analytics.productzillaacademy.com
        volumes:
            - ./volumes/kibana_data:/usr/share/kibana/data
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        networks:
            default:

    apm-es-server:
        image: docker.elastic.co/apm/apm-server:8.12.2
        command: >
            apm-server -e
              -E apm-server.rum.enabled=true
              -E apm-server.auth.api_key.enabled=true
              -E setup.kibana.host=kibana:5601
              -E setup.template.settings.index.number_of_replicas=0
              -E apm-server.kibana.enabled=true
              -E apm-server.kibana.host=kibana:5601
              -E apm-server.kibana.username=kibana_system
              -E apm-server.kibana.password=${ELASTIC_KIBANA_PASSWORD}
              -E output.elasticsearch.hosts=["elasticsearch:9200"]
              -E output.elasticsearch.username=elastic
              -E output.elasticsearch.password=${ELASTIC_SUPERADMIN_PASSWORD}
        ports:
            - '8200:8200'
        depends_on:
            - elasticsearch
        networks:
            default:

    init:
        image: appropriate/curl
        restart: on-failure
        depends_on:
            - elasticsearch
        entrypoint: [sh, -c]
        command:
            - |
                until curl -u elastic:${ELASTIC_SUPERADMIN_PASSWORD} http://elasticsearch:9200  > /dev/null; do sleep 1; done &&
                curl -u elastic:${ELASTIC_SUPERADMIN_PASSWORD} -v -X  POST -H "Content-Type:application/json" "http://elasticsearch:9200/_security/user/apm_system/_password" -d '{"password":"${ELASTIC_APM_PASSWORD}"}' &&
                curl -u elastic:${ELASTIC_SUPERADMIN_PASSWORD} -v -X  POST -H "Content-Type:application/json" "http://elasticsearch:9200/_security/user/kibana_system/_password" -d '{"password":"${ELASTIC_KIBANA_PASSWORD}"}'
        networks:
            default:
