export enum CurrentPageEvent {
    null = 'null',
    index = 'index',
    boostbot = 'boostbot',
    dashboard = 'dashboard',
    sequences = 'sequences',
    sequencesV2 = 'sequences-v2',
    inbox = 'inbox',
    'influencer-manager' = 'influencer-manager',
    guide = 'guide',
    account = 'account',
    pricing = 'pricing',
    upgrade = 'upgrade',
    login = 'login',
    signup = 'signup',
    payments = 'payments',
    influencer = 'influencer',
    campaigns = 'campaigns',
    admin = 'admin',
    performance = 'performance',
    error = 'error',
    preview = 'preview',
    logout = 'logout',
}
