// Generated by https://quicktype.io
// types come from Stripe dashboard, 'webhooks' section, then click registered URL and view events

import type { RelayAccountPlanMetadata } from 'types/appTypes';
export interface CustomerSubscriptionCreated {
    id: string;
    object: string;
    api_version: string;
    created: number;
    data: Data;
    livemode: boolean;
    pending_webhooks: number;
    request: Request;
    type: 'customer.subscription.created';
}

interface Data {
    object: DataObject;
}

interface DataObject {
    id: string;
    object: string;
    application: null;
    application_fee_percent: null;
    automatic_tax: AutomaticTax;
    billing_cycle_anchor: number;
    billing_thresholds: null;
    cancel_at: null;
    cancel_at_period_end: boolean;
    canceled_at: null;
    collection_method: string;
    created: number;
    currency: string;
    current_period_end: number;
    current_period_start: number;
    customer: string;
    days_until_due: null;
    default_payment_method: null;
    default_source: null;
    default_tax_rates: any[];
    description: null;
    discount: null;
    ended_at: null;
    items: Items;
    latest_invoice: string;
    livemode: boolean;
    metadata: DatumMetadata;
    next_pending_invoice_item_invoice: null;
    on_behalf_of: null;
    pause_collection: null;
    payment_settings: PaymentSettings;
    pending_invoice_item_interval: null;
    pending_setup_intent: null;
    pending_update: null;
    plan: Plan;
    quantity: number;
    schedule: null;
    start_date: number;
    status: string;
    test_clock: null;
    transfer_data: null;
    trial_end: null;
    trial_settings: TrialSettings;
    trial_start: null;
}

interface AutomaticTax {
    enabled: boolean;
}

interface Items {
    object: string;
    data: Datum[];
    has_more: boolean;
    total_count: number;
    url: string;
}

interface Datum {
    id: string;
    object: string;
    billing_thresholds: null;
    created: number;
    metadata: DatumMetadata;
    plan: Plan;
    price: Price;
    quantity: number;
    subscription: string;
    tax_rates: any[];
}

type DatumMetadata = unknown;

interface Plan {
    id: string;
    object: string;
    active: boolean;
    aggregate_usage: null;
    amount: number;
    amount_decimal: string;
    billing_scheme: string;
    created: number;
    currency: string;
    interval: string;
    interval_count: number;
    livemode: boolean;
    metadata: PlanMetadata;
    nickname: null;
    product: string;
    tiers_mode: null;
    transform_usage: null;
    trial_period_days: null;
    usage_type: string;
}

type PlanMetadata = RelayAccountPlanMetadata;

interface Price {
    id: string;
    object: string;
    active: boolean;
    billing_scheme: string;
    created: number;
    currency: string;
    custom_unit_amount: null;
    livemode: boolean;
    lookup_key: null;
    metadata: PlanMetadata;
    nickname: null;
    product: string;
    recurring: Recurring;
    tax_behavior: string;
    tiers_mode: null;
    transform_quantity: null;
    type: string;
    unit_amount: number;
    unit_amount_decimal: string;
}

interface Recurring {
    aggregate_usage: null;
    interval: string;
    interval_count: number;
    trial_period_days: null;
    usage_type: string;
}

interface PaymentSettings {
    payment_method_options: null;
    payment_method_types: null;
    save_default_payment_method: string;
}

interface TrialSettings {
    end_behavior: EndBehavior;
}

interface EndBehavior {
    missing_payment_method: string;
}

interface Request {
    id: string;
    idempotency_key: string;
}
