// Generated by https://quicktype.io

export interface YoutubeVideoDataRaw {
    success: boolean;
    video_info: VideoInfo;
}

export interface VideoInfo {
    video_id: string;
    channel_id: string;
    title: string;
    published_at: string;
    duration: string;
    views: number;
    likes: number;
    comments: number;
    genre: string;
    thumbnail: string;
    description: string;
    keywords: string[];
    subtitles: Subtitle[];
    comments_tabs: CommentsTab[];
}

export interface CommentsTab {
    type: string;
    cursor: string;
}

export interface Subtitle {
    vss_id: string;
    language_code: string;
    name: string;
    fetch_url: string;
}
