version: '3'
services:
    redis:
        image: redis
        ports:
            - '6379:6379'
    serverless-redis-http:
        image: hiett/serverless-redis-http:latest
        ports:
            - 8079:80
        environment:
            SRH_MODE: env
            SRH_TOKEN: abcdefghijklmnopqrstuvwxyz123456
            SRH_CONNECTION_STRING: 'redis://redis:6379' # Using `redis` hostname since they're in the same Docker network.
