CREATE TABLE "public"."sales" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "value" numeric NOT NULL,
  "campaign_id" uuid,
  "company_id" uuid NOT NULL
);


CREATE UNIQUE INDEX campaign_sales_pkey ON public.sales USING btree (id);

ALTER TABLE "public"."sales" ADD CONSTRAINT "campaign_sales_pkey" PRIMARY KEY USING INDEX "campaign_sales_pkey";

ALTER TABLE "public"."sales" ADD CONSTRAINT "sales_campaign_id_fkey" FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE SET NULL NOT VALID;

ALTER TABLE "public"."sales" VALIDATE CONSTRAINT "sales_campaign_id_fkey";

ALTER TABLE "public"."sales" ADD CONSTRAINT "sales_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."sales" VALIDATE CONSTRAINT "sales_company_id_fkey";
