CREATE TABLE "public"."company_categories" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "category" text NOT NULL,
  "company_id" uuid NOT NULL
);


ALTER TABLE "public"."company_categories" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX company_categories_pkey ON public.company_categories USING btree (id);

ALTER TABLE "public"."company_categories" ADD CONSTRAINT "company_categories_pkey" PRIMARY KEY USING INDEX "company_categories_pkey";

ALTER TABLE "public"."company_categories" ADD CONSTRAINT "company_categories_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."company_categories" VALIDATE CONSTRAINT "company_categories_company_id_fkey";
