run-name: Run db-deploy workflow by @${{ github.actor }}

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
    SUPABASE_SCANNER_BUFFER_SIZE: 5mb

jobs:
    deploy:
        runs-on: ubuntu-22.04
        environment: production
        steps:
            - uses: actions/checkout@v3

            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            - name: Verify supabase cli version
              run: supabase -v

            - name: Create supabase config file
              run: cp supabase/config.toml.example supabase/config.toml

            - run: |
                  supabase link --project-ref=$SUPABASE_PROJECT_ID
                  supabase db push
