# name: SonarScanner

# on:
#     push:
#         branches:
#             - '**'
#             - '!main'
#             - '!master'

# jobs:
#     sonar-scanner:
#         runs-on: ubuntu-latest

#         steps:
#             - uses: actions/checkout@v3
#             - name: SonarScanner
#               uses: sonarsource/sonarqube-scan-action@master
#               env:
#                 SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
#                 SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#                 SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
