name: SonarScanner

on:
    push:
        branches:
            - '**'
            - '!main'
            - '!master'

jobs:
    sonar-scanner:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: SonarScanner
              uses: sonarsource/sonar-scan-action@v1
              with:
                sonar-organization: ${{ secrets.SONAR_ORGANIZATION }}
                sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
                sonar-login: ${{ secrets.SONAR_LOGIN }}
