run-name: Run staging workflow by @${{ github.actor }}

on:
    push:
    workflow_dispatch:

env:
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
    STAGING_PROJECT_ID: ${{ env.STAGING_PROJECT_ID }}
    SUPABASE_SCANNER_BUFFER_SIZE: 5mb

jobs:
    supabase-test:
        runs-on: ubuntu-22.04
        environment: staging
        steps:
            - uses: actions/checkout@v3

            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            - name: Verify supabase cli version
              run: supabase -v

            - name: Create supabase config file
              run: cp supabase/config.toml.example supabase/config.toml

            - run: |
                supabase link --project-ref=$STAGING_PROJECT_ID
                supabase db push
